version: '3.7'

services:
  # nginx - web server
  nginx:
    build:
      context: .
      dockerfile: ./docker-config/nginx/Dockerfile
    env_file:
      - ./app/.env
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/project/app/public:cached
  # php - personal home page
  php:
    build:
      context: .
      dockerfile: ./docker-config/alpine-php-dev-overlay/Dockerfile
    depends_on:
      - "mariadb"
    env_file:
      - ./app/.env
      - ./app/env/.env-mariadb
    expose:
      - "9000"
    links:
      - mariadb
    volumes:
      - ./app:/var/www/project/app:consistent
      - ./app/vendor:/var/www/project/app/vendor:delegated
      - ./app/var/logs:/var/www/project/app/var/logs:delegated
      - ./app/var/cache:/var/www/project/app/var/cache:delegated
  # mariadb - database
  mariadb:
    build:
      context: .
      dockerfile: ./docker-config/mariadb/Dockerfile
    env_file: 
      - ./app/env/.env-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
